name: Code Evaluation CI

on:
  push:
    branches:
      - main
    paths:
      - 'solutions/**'

jobs:
  evaluate-code:
    runs-on: self-hosted

    steps:
      - name: 1. Checkout Public Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 2. Checkout Private Test Cases Repo
        uses: actions/checkout@v4
        with:
          repository: spirit-amir/intern-challenge-private
          token: ${{ secrets.GH_TOKEN }}
          path: private-repo

      - name: 3. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 4. Install Dependencies
        run: pip install requests

      - name: 5. Find All Solutions for Submitter
        id: solution_files
        run: |
          SUBMITTER_DIR="solutions/${{ github.actor }}"
          echo "Checking for all solutions from user: ${{ github.actor }}"
          echo "Looking in directory: $SUBMITTER_DIR"

          if [ -d "$SUBMITTER_DIR" ]; then
            ALL_FILES=$(find "$SUBMITTER_DIR" -type f | xargs)
            echo "Found files to test: $ALL_FILES"
            echo "files=$ALL_FILES" >> $GITHUB_OUTPUT
          else
            echo "No solution directory found for user ${{ github.actor }}. Nothing to test."
            echo "files=" >> $GITHUB_OUTPUT
          fi

      - name: 6. Run Evaluation for All Found Solutions
        env:
          JUDGE0_API_KEY: ${{ secrets.JUDGE0_API_KEY }}
        run: |
          shopt -s globstar
          set +e
          for file in solutions/**; do
            if [ -f "$file" ] && [[ "$file" != *.md ]]; then
              echo "Evaluating solution: $file"
              python scripts/evaluate.py "$file"
              echo "==========================="
            fi
          done
